Revert "soong: Disable clang-tidy"
--- FAIL: TestTidyChecks (0.18s)
    --- FAIL: TestTidyChecks/caseTidyChecks (0.00s)
panic: couldn't find rule "clangTidy".
all rules:
android/soong/cc.cc
android/soong/cc.toc
android/soong/cc.strip
android/soong/cc.ld
android/soong/android.Cp
android/soong/android.licenseMetadataRule [recovered]
        panic: couldn't find rule "clangTidy".

This reverts commit 09c04ee7007bb343d341b19f9920c10a31cede33.